### ISSUE TITLE
cta套利demo

### ISSUE THREAD

**Issue by haotin** [msincenselee/vnpy#1]
李老师  能否把您套利的demo共享一个 去掉核心的代码  这样比较容易学习一点

**Comment by wycwywfwa** [comment]
围观一下，啥都没有……

**Comment by msincenselee** [comment]
下周发布一个demo。

________________________________

**Comment by msincenselee** [comment]
我的套利主要结合网格交易。对于标准套利合约，跟单一合约的交易方法没什么区别的。

**Comment by jeffereylj** [comment]
请问demo 是放在哪个目录下面的呢？

**Comment by msincenselee** [comment]
需要的同学，私信加V 28888502，我给你们。
