### ISSUE TITLE
 No module named 'vnpy.trader.app.ctaStrategy.ctaRenkoBar'

### ISSUE THREAD

**Issue by dh12306** [msincenselee/vnpy#9]
File "xxx\vnpy\trader\app\dataRecorder\drEngine.py", line 22, in <module>
    from vnpy.trader.app.ctaStrategy.ctaRenkoBar import CtaRenkoBar
ImportError: No module named 'vnpy.trader.app.ctaStrategy.ctaRenkoBar'

少个文件吗 @msincenselee

**Comment by msincenselee** [comment]
对，renkobar我还没开源，你可以注解掉它得引用就行了。
